name: Unit tests
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.run_phase }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        run_phase: [GCC, GCC_ASAN_UBSAN, CLANG, CLANG_ASAN_UBSAN]
    steps:
      - name: Repository checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - name: Install build dependencies
        run: sudo -E .github/workflows/unit_tests.sh SETUP
      - name: Build & test (${{ matrix.run_phase }})
        run: sudo -E .github/workflows/unit_tests.sh RUN_${{ matrix.run_phase }}
  coveralls:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    if: github.repository == 'evverx/elfutils'
    steps:
      - name: Repository checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - name: Ubuntu setup
        run: sudo -E .github/workflows/unit_tests.sh SETUP
      - run: |
          autoreconf -i -f
          ./configure --enable-maintainer-mode --enable-gcov
          make -j$(nproc) V=1
          make V=1 VERBOSE=1 check
          make V=1 coverage
      - name: Coveralls
        uses: coverallsapp/github-action@9ba913c152ae4be1327bfb9085dc806cedb44057
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./elfutils.lcov
